### PR TITLE
add mandatory reviewer in path

### PR DESCRIPTION
**Pull request by Wingless-Archangel**

### CODE REVIEW

**Comment by robertoaloi** [comment]
Property-based tests correctly pass, thanks!

**Comment by Wingless-Archangel** [comment]
not merge since we will pull from upstream instead.

**Comment by robertoaloi** [comment]
Hi @Wingless-Archangel What do you mean exactly? GitHub *is* the upstream, "source of truth" version. Or?

**Comment by robertoaloi** [comment]
Ah, I now see this PR was pointing to the fork's "master" branch. Never mind my comment. :)

**Pull request closed without merging**
